version: '2'
services:
    tclinica-app:
        image: tclinica
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://tclinica-mariadb:3306/tclinica
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tclinica-mariadb:
        extends:
            file: mariadb.yml
            service: tclinica-mariadb
