version: '2'
services:
    usingpgre-app:
        image: tclinica
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://usingpgre-postgresql:5432/usingPgre
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tclinica-postgresql:
        extends:
            file: postgresql.yml
            service: tclinica-postgresql
